---
title: Daniel Fiott
timezone: Europe/Amsterdam
collections:
  posts:
    title: Posts
    output: true
  products:
    title: Products
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: _pages
  values:
    permalink: "/:basename:output_ext"
theme_version: 1.0.4
logo: 
description: Thoughts, Stories and Ideas
baseurl: 
url: 
twitter: 
facebook: 
instagram: https://www.instagram.com/dan.fiott/
markdown: kramdown
permalink: pretty
paginate: 11
sass:
  style: compressed
gems:
- jekyll-paginate
- jekyll/tagging
include:
- _pages
exclude:
- vendor
- Gemfile
- Gemfile.lock
tag_page_dir: tag
tag_page_layout: tag_page
tag_permalink_style: pretty
authors:
  ahmad:
    name: Daniel Fiott
    bio: 
    gravatar: 
    email: 
    website: 
    github: 
    twitter: 
